### ISSUE TITLE
Question: PEST++

### ISSUE THREAD

**Issue by Lau397** [LudovicSchorpp/FloPy-guide-#1]
Hi Ludovic, 

First of all sorry this is a question not exactly an issue ☺

Just to let you know initially that, as a newbie on Python/FloPy/PEST++, your repositories have been quite helpful for me :), so thank you in advance!

I have some questions just in case you know (I hope so!) in regards to PEST++. 

I'm trying to do a model calibration using PESTPP-GLM however, I'm not sure how to proceed because recently I've found myself a bit confused especially, the more I read. I'm wondering how can I add my (real real 4 real measurements taken on the field!) observations into PEST? I've seen that we can add those model generated observations but I haven't seen yet how to add the real ones? Do you know in your experience if that is possible? If so, could you please let me know how?

Second, I'd like to add SVD and Tikhonov regularization to get better results with PESTPP-GLM but I am confused as well on that step. Do you know if it is enough (and if it's the right way) to add them using `pst.pestpp_options["..."]` and then write on the control file and re-run? 

I guess that's all for now

Thanks again! :)

**Comment by LudovicSchorpp** [comment]
Hi Laura !

Thank you for your interest ! (I didn't know that some people was really looking through my notebooks !)
Before all, I'm also pretty newbie with FloPy and Pest++ (I started using them this summer for my master).

And yes, I totally understand what is troubling you with the observations import which can be tricky. You have various solutions but I propose you to do the import of "fake" observations (model generated) and after your PstFrom object (let's call it pf) have an attribute that is called "obs_dfs". With this attribute, you can retrieve the dataframes which contain the observations infos.

**Comment by LudovicSchorpp** [comment]
Hi Laura !

Thank you for your interest ! (I didn't know that some people was really looking through my notebooks !)
Before all, I'm also pretty newbie with FloPy and Pest++ (I started using them this summer for my master).

And yes, I totally understand what is troubling you with the observations import which can be tricky. You have various solutions but I propose you to do the import of "fake" observations (model generated yes but at the exact position of your real observations) and after your PstFrom object (let's call it pf) have an attribute that is called "obs_dfs". With this attribute, you can retrieve the dataframes which contain the observations infos.

So, what you can do (after adding the observations with pf.add_observations), is pf.obs_dfs[0] which will open you the first dataframe observations group. In this df you have the observation name, the weight, etc AND the observation value ! And you can modify it directly. Of course, this requires importing your false observations at the locations of your true observations.

I'm not sure if I'm clear but this is a way to add "real" observations (I have another one which requires to modify directly the observations file (csv file) before adding it with PyEmu).

The SVD regularization is always activated by default when th setup is make with PyEmu ! (as well as SVD assist if you setup on SVD assist variable, as you say with pestpp_options["..."]). In my example SVD is activated.
However, in order to activate Tikhonov, you will need some prior data (or you can assume that the initial values are the best guess for your parameter). The setup is really simple ! 
1. Build your pst object with : pst = pf.build_pst("{}.pst".format(case)) where you indicate the name of your pest file
2. Change parameters initial value with you best guess (pst.parameter_data.parval1)
3. Apply tikhonov with the following command : pyemu.helpers.zero_order_tikhonov(pst)

I hope this helps you out a little.

Let me know if you have other questions ! You can send them directly to my mail : ludovic.schorpp@unine.ch
